### ISSUE TITLE
How do i have multiple details?

### ISSUE THREAD

**Issue by VisualEhrmanntraut** [MinnDevelopment/Java-DiscordRPC#13]
Hello, i want mulitple details except for the state and the details(i want mulitple lines) how do i do that?

**Comment by m-sterling** [comment]
The Discord RPC library only allows one line for the state and one line for the details. Maybe try opening a ticket on the [Discord RPC library repo](https://github.com/discordapp/discord-rpc) and make that a suggestion?

**Comment by MinnDevelopment** [comment]
As @kkirigaya mentioned, this is not the place to ask for features.
