### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by deathbeam** [MinnDevelopment/Java-DiscordRPC#14]
Hello, I am trying to find some Discord RPC library for Java right now, and only one I stumbled upon is also on Maven Repository. I would prefer to use this one, but as it is not on Maven Repository, it just complicates things.
Are there any plans to upload this library to Maven Repository?

**Comment by m-sterling** [comment]
Hey there,

Obviously I'm not Minn, so I can't answer if it'll be on the "official" Maven repo, but just because it's not there doesn't mean you can't use Maven. The repo and all of its code is accessible via the JitPack Maven repository.

This link will have more info on how to add the JitPack repository to your `pom.xml` file: [JitPack](https://jitpack.io/#MinnDevelopment/discord-rpc)

If you have further questions, don't hesitate to ask!

**Comment by MinnDevelopment** [comment]
Since jitpack does everything that is needed I don't feel like moving it onto maven central/jcenter.
You can use the jitpack resolver as mentioned by @kkirigaya

**Comment by deathbeam** [comment]
Ooh, thank you, didn't knew about JitPack. That thing is awesome :o Anyway, got the dependency working now, so closing this issue. Ty for fast reply.

**Comment by deathbeam** [comment]
Reopening this because I can't get any dependency files. It looks like that jitpack current cannot build the project?

```
Build starting...
Start: Sat Feb 3 19:38:25 UTC 2018
Git:
v2.0.1-31-g49b2304
commit 49b23040c60fb5819d8f03ccf4bbd4b6785daf12
Author: Chris Marsh 
Date:   Wed Nov 22 16:12:37 2017 -0800

    wip updating build script



ERROR:
No build file found. Looking for Gradle/Maven/Sbt/Lein build file in the root of the project
See the documentation at https://jitpack.io/docs/
Files: 
CMakeLists.txt
LICENSE
README.md
appveyor.yml
build.py
documentation
examples
include
src
2018-02-03T19:38:25.586295388Z
Exit code: 1
No build artifacts found
```

**Comment by m-sterling** [comment]
Sorry to hear that! Mind posting your `pom.xml` file here so I can take a look at it? Thanks!

**Comment by deathbeam** [comment]
So, here is the [parent pom](https://github.com/runelite/runelite/blob/master/pom.xml).

What I added there is:
```xml
		<repository>
			<id>jcentral</id>
			<url>https://jcenter.bintray.com</url>
			<name>jcenter</name>
		</repository>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
			<name>jitpack</name>
		</repository>
```

Before `</repositories>`

Here is the [child project pom](https://github.com/runelite/runelite/blob/master/runelite-client/pom.xml)

Where I actually want to use the Discord RPC.

I added

```xml
		<dependency>
			<groupId>com.github.MinnDevelopment</groupId>
			<artifactId>discord-rpc</artifactId>
			<version>v1.3.1</version>
		</dependency>
```

under

```xml
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
```

It looks like it should be working, but Maven cannot resolve the `discord-rpc` dependency. Tree output from the ~/.m2

```
MinnDevelopment
└── discord-rpc
    └── v1.3.1
        ├── discord-rpc-v1.3.1.jar.lastUpdated
        └── discord-rpc-v1.3.1.pom.lastUpdated

2 directories, 2 files
```

I tried other versions/commits/branches but deleted the MinnDevelopment directory in order to try re-fetch it, but no success as you can see above.

**Comment by deathbeam** [comment]
Oh, oops, my fault `java-discord-rpc` not `discord-rpc` :man_facepalming:
