### ISSUE TITLE
No message no error ...

### ISSUE THREAD

**Issue by Jerem584** [MinnDevelopment/Java-DiscordRPC#17]
hey!

i can't figure out the problem. using the first basic, no message no error. dll added to the project.

**Comment by m-sterling** [comment]
Can you be a bit clearer in your issue? Not a word of what you said was understood. Which example are you trying? And you're saying it doesn't work but you don't get an error?

**Comment by Jerem584** [comment]
https://github.com/MinnDevelopment/java-discord-rpc/blob/master/examples/java/ml/yuuki/chris/rpc/examples/WindowTest.java

I can't make a rich presence ... No error... console is clear.

**Comment by MinnDevelopment** [comment]
Did you set an application id?

**Comment by Jerem584** [comment]
get a ready for my bot. presence not updating.

**Comment by Jerem584** [comment]
I'm an idiot. i'm sorry guys, can we have a list for applications id ?

**Comment by m-sterling** [comment]
Since you seem to be using my example, you have to pass the app ID as an argument. Which IDE are you using?

**Comment by Jerem584** [comment]
eclipse ... but it work now
