### ISSUE TITLE
Issues with Unicode

### ISSUE THREAD

**Issue by CertainLach** [MinnDevelopment/Java-DiscordRPC#19]
I.e setting state to `В главном меню` results to this:
![default](https://user-images.githubusercontent.com/6235312/37993908-6538785e-3229-11e8-9854-324bc3674d9c.png)
displayed in discord

**Comment by m-sterling** [comment]
This is most likely an issue with the [official Discord RPC library](https://github.com/discordapp/discord-rpc). I suggest opening an issue on that repo [here](https://github.com/discordapp/discord-rpc/issues/new).

**Comment by CertainLach** [comment]
```java
	public Pointer state;

	public void setState(String state){
		byte[] arr=state.getBytes(Charset.forName("UTF-8"));
		this.state = new Memory(arr.length+1);
		int i=0;
		for(;i<arr.length;i++)
			this.state.setByte(i,arr[i]);
		this.state.setByte(i, (byte) 0);
	}
```
![default](https://user-images.githubusercontent.com/6235312/38013172-9aed117c-327d-11e8-84bc-ef12463cad4b.png)

**Comment by CertainLach** [comment]
Solved for me:
https://github.com/MinnDevelopment/java-discord-rpc/pull/20

**Comment by MinnDevelopment** [comment]
This is not an issue with the library itself.

**Comment by FlickySH** [comment]
Facing the same issue
