### ISSUE TITLE
Natives not found even tho they're in /src/main/resources

### ISSUE THREAD

**Issue by bddvlpr** [MinnDevelopment/Java-DiscordRPC#23]
I've setup this project using Maven and it worked before but now it stopped detecting the natives, i've tried reinstalling them in the correct folder but it still gives an exception.

```
java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': dlopen(libdiscord-rpc.dylib, 9): image not found
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:169)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:242)
	at com.sun.jna.Library$Handler.<init>(Library.java:140)
	at com.sun.jna.Native.loadLibrary(Native.java:368)
	at com.sun.jna.Native.loadLibrary(Native.java:353)
	at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
```

**Comment by m-sterling** [comment]
Hi StijnSimons,

The natives are not found in this repository. They're found in the [MinnDevelopment/discord-rpc-release](https://github.com/MinnDevelopment/discord-rpc-release) repo. Once you add that repo to your Maven dependencies, you need to add the natives directory to your buildpath.

(This is taken from [this](https://stackoverflow.com/a/19352101) SO page and [this](http://wiki.lwjgl.org/wiki/Setting_Up_LWJGL_with_IntelliJ_IDEA.html) wiki page which explain how to add the natives for LWJGL; the process is exactly the same for the RPC natives)

For Eclipse:

- Right click on the "JRE System Library" of your project, and click "Build Path" -> "Configure Build Path".
- Include the native libraries to your project in the Build Path Configurer by clicking the "Native library location" which can be seen in the JRE System Library dropdown menu.
- Click on "Edit...", which will be the only button clickable in that general area.
- A file explorer will pop up. Navigate to the location of your RPC native folder and include the folder named [Your OS here].

For IntelliJ:

- We add the needed jar files by going to File -> Project Structure:
- In the Modules page, in the Dependencies tab, click on the green plus symbol and choose "JARs or directories":
- Navigate to and select the JARs for your OS

Hopefully this works for you. Please let me know if you continue to experience this issue!

**Comment by bddvlpr** [comment]
Same error, it is in the dependencies tho.
![image](https://user-images.githubusercontent.com/17461028/40745040-a97bb9a4-6456-11e8-9ab3-b2141ff5dfb6.png)

**Comment by m-sterling** [comment]
Just because it's in the dependencies doesn't mean it's included in the build path. Maven is intended for use with JAR files, not the RPC resources. Using Maven for them works for auto-updating to the latest version of them and such, but you still need to follow the above instructions to include them in your build path.

**Comment by bddvlpr** [comment]
Tried that. Same error.

**Comment by bddvlpr** [comment]
Just opened an old project using java-discord-rpc.
For some reason this works, even though everything is the same.

**Comment by bddvlpr** [comment]
For some reason, adding
```
<dependency>
        <groupId>net.java.dev.jna</groupId>
        <artifactId>jna</artifactId>
        <version>4.5.1</version>
</dependency>
```
fixxed this.

**Comment by m-sterling** [comment]
Yep, this library depends on JNA, so not having it would definitely cause some issues.

Glad you were able to figure it out!

**Comment by bddvlpr** [comment]
It did have the dependency, it was just an older version.
