### ISSUE TITLE
jcenter returning 502

### ISSUE THREAD

**Issue by LA** [MinnDevelopment/Java-DiscordRPC#36]
Tragic to see as I'm compiling (on an extremely strict deadline) that https://jcenter.bintray.com/club/minnced/java-discord-rpc/2.0.1/java-discord-rpc-2.0.1.pom is returning 502, so I can't use it in maven.

**Comment by MinnDevelopment** [comment]
Works fine on my end. Looks like this was just a temporary issue for bintray's backend server.
