### ISSUE TITLE
How to utilize Discord_Initialize() to connect to second local instance of Discord

### ISSUE THREAD

**Issue by Saelack** [MinnDevelopment/Java-DiscordRPC#38]
Attempting to test locally for Rich Presence game joining, and utilizing Canary for a second instance of Discord.  However, I am not seeing how to attach to this second instance - the Discord API seems to mention a 5th argument, "pipe", as a way of connecting to an alternate instance.

Am I missing something?

**Comment by MinnDevelopment** [comment]
There was a pipe argument available at a time but no release for it was ever made. The change was reverted in this [commit](https://github.com/discordapp/discord-rpc/commit/c59fd6df20c6904ab39f026e87af1dd90fcac7ff) and has not received a release.

**Comment by Saelack** [comment]
So how would I utilize this functionality - or is a release planned including this in a release?

**Comment by MinnDevelopment** [comment]
This library only adds an interface for the official SDK, if they decide not to make a release with this feature I can't either. You will have to ask them for any further details on its status.

**Comment by Saelack** [comment]
Ahh, I understand my confusion - I thought the documentation was correct, and missed that the commit you referred to was from the official SDK.

Many thanks.
