### ISSUE TITLE
Instantly crashes with no exception/warning when Discord is not installed.

### ISSUE THREAD

**Issue by s5bug** [MinnDevelopment/Java-DiscordRPC#4]
Based on it being a segfault, this may need to be moved to Discord's lib.

**Comment by MinnDevelopment** [comment]
I don't think I can prevent that in this binding. I'm open for suggestions though.

**Comment by s5bug** [comment]
I think I'm going to take it up at discord-rpc.

**Comment by s5bug** [comment]
Ah. It was my misunderstanding that it was on startup.
