### ISSUE TITLE
About secret

### ISSUE THREAD

**Issue by cool9850311** [MinnDevelopment/Java-DiscordRPC#42]
how can I avoid my app to be used on other people's rpc?
they can get our client id in the browser

**Comment by m-sterling** [comment]
Client IDs are not meant to be private/secret, as they can be easily accessed through the Discord app developer tools, as you pointed out, so there is no real way to avoid this. Additionally, Discord's RPC library is now deprecated in favour of their [GameSDK](https://discordapp.com/developers/docs/game-sdk/sdk-starter-guide), so I would suggest moving to that before this RPC library no longer functions altogether.

**Comment by cool9850311** [comment]
thx:)
