### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by PLRpower** [MinnDevelopment/Java-DiscordRPC#45]
Can you add a support for buttons in you next version please ? Thank you !
!
[exempleofbutton](https://user-images.githubusercontent.com/66971495/133857337-5340340e-6423-4919-b5d3-00ae850fcc1f.png)

**Comment by MinnDevelopment** [comment]
This library is only a binding for [discord-rpc](/discord/discord-rpc) and cannot offer any functionality beyond the scope of the original project by discord. You have to use a custom implementation or the [Game SDK](https://discord.com/developers/docs/game-sdk/sdk-starter-guide) which will never be supported by this library.
