### ISSUE TITLE
Darwin support is working, but doesn't have a Release

### ISSUE THREAD

**Issue by AgentEpsilon** [MinnDevelopment/Java-DiscordRPC#7]
If there was a Github release tag that included the Darwin dylib, then projects could support macOS.

**Comment by MinnDevelopment** [comment]
The release of 1.2 is awaiting the documentation changes of #6 in the meantime you can use the most recent commit hash as version.
Example for gradle: `compile 'com.github.MinnDevelopment:Java-DiscordRPC:ac5097e'` where `ac5097e` is the latest commit.
